function [V_S,I_S]=cableCalc(V_R,I_R,cableID)

% Voltage, sending end
V_inc=(V_R+cableData(cableID).Z_C*I_R)...
    *exp(cableData(cableID).gamma.*cableData(cableID).x)/2;        % Incident voltage [V]
V_ref=(V_R-cableData(cableID).Z_C*I_R)...
    *exp(-cableData(cableID).gamma.*cableData(cableID).x)/2;       % Reflected voltage [V]
V_S=V_inc+V_ref;                                                   % Sending voltage [V]

% Current, sending end
I_S=((V_R./cableData(cableID).Z_C+I_R)...
    *exp(cableData(cableID).gamma.*cableData(cableID).x)/2)...
    -((V_R./cableData(cableID).Z_C-I_R)...
    *exp(-cableData(cableID).gamma.*cableData(cableID).x)/2);      % Sending current [A]
end