function [V_S,I_S]=cableCalc(V_R,I_R,cable,cableID)

% Voltage, sending end
V_inc=(V_R+cable(cableID).Z_C*I_R)...
    *exp(cable(cableID).gamma.*cable(cableID).l)/2;        % Incident voltage [V]
V_ref=(V_R-cable(cableID).Z_C*I_R)...
    *exp(-cable(cableID).gamma.*cable(cableID).l)/2;       % Reflected voltage [V]
V_S=V_inc+V_ref;                                                   % Sending voltage [V]

% Current, sending end
I_S=((V_R./cable(cableID).Z_C+I_R)...
    *exp(cable(cableID).gamma.*cable(cableID).l)/2)...
    -((V_R./cable(cableID).Z_C-I_R)...
    *exp(-cable(cableID).gamma.*cable(cableID).l)/2);      % Sending current [A]
end