function [V_S,I_S]=cableCalc(V_R,I_R,dataStruct,cableID)

% Voltage, sending end
V_inc=(V_R+dataStruct(cableID).Z_C*I_R)...
    *exp(dataStruct(cableID).gamma.*dataStruct(cableID).l)/2;        % Incident voltage [V]
V_ref=(V_R-dataStruct(cableID).Z_C*I_R)...
    *exp(-dataStruct(cableID).gamma.*dataStruct(cableID).l)/2;       % Reflected voltage [V]
V_S=V_inc+V_ref;                                                   % Sending voltage [V]

% Current, sending end
I_S=((V_R./dataStruct(cableID).Z_C+I_R)...
    *exp(dataStruct(cableID).gamma.*dataStruct(cableID).l)/2)...
    -((V_R./dataStruct(cableID).Z_C-I_R)...
    *exp(-dataStruct(cableID).gamma.*dataStruct(cableID).l)/2);      % Sending current [A]
end