function timeLine=setTimeLine(leapYear)
    if ~exist('leapYear','var'), leapYear = 0; end    % Leap year is off by default
    % Set timeline
    monthList={1,'January';...
               2,'February';...
               3,'March';...
               4,'April';...
               5,'May';...
               6,'June';...
               7,'July';...
               8,'August';
               9,'September';...
               10,'October';...
               11,'November';...
               12,'December'};
    [sel,ok] = listdlg('PromptString','Choose months:',...
        'SelectionMode','single',...
        'ListString',monthList(:,2),...
        'Name','Select timeline',...
        'ListSize',[200,250],...
        'SelectionMode','multiple');
    if ok~=true
        error('No case selected.');
    end
    selectedMonths=cell2mat(monthList(sel,1));
    
    monthsStart2End=[1      744;...
                     745    1416;...
                     1417   2160;...
                     2161   2880;...
                     2881   3624;...
                     3625   4344;...
                     4345   5088;...
                     5089   5832;...
                     5833   6552;...
                     6553   7296;...
                     7297   8016;...
                     8017   8760];
    
    if leapYear
        monthsStart2End(2,2)=1440;
        monthsStart2End(3:end,:)=monthsStart2End(3:end,:)+24;
    end
    filledUntil=0;
    timeLine=zeros(1,sum(diff(monthsStart2End(selectedMonths,:),[],2)+1));
    for iSel=selectedMonths'
        intervalForMonth=filledUntil+1:filledUntil+diff(monthsStart2End(iSel,:),[],2)+1;
        timeLine(intervalForMonth)=monthsStart2End(iSel,1):monthsStart2End(iSel,2);
        filledUntil=filledUntil+diff(monthsStart2End(iSel,:),[],2)+1;
    end

    fprintf('Timeline set. ');
    if length(selectedMonths)==12
        fprintf('Selected months: All year');
    else
        fprintf('Selected months: %s',strjoin(monthList(sel,2),', '));
    end
    fprintf('.\n');
end