% Plot voltage histogram
% Known issues: - Cannot handle bus 1
%               - Limit lines might cause strange scaling

histBusNr = input('Enter node number for histogram: ');
fprintf('\n');
figure;
monthsStart2End=[1      744;...
                 745    1416;...
                 1417   2160;...
                 2161   2880;...
                 2881   3624;...
                 3625   4344;...
                 4345   5088;...
                 5089   5832;...
                 5833   6552;...
                 6553   7296;...
                 7297   8016;...
                 8017   8760];           

for iMonth = 12:-1:1
    monthStart=monthsStart2End(iMonth,1);   % Month start
    monthEnd=monthsStart2End(iMonth,2);     % Month end
    [vHistCount,vHistEdges] = histcounts(abs(resultSet.U_hist(histBusNr,...
        timeLine>=monthStart & timeLine<=monthEnd)*(TransformerData.U_sec_base/sqrt(3))));
    vHistCount(vHistCount == 0) = NaN;      % Ignore zero values
    vHistCenters=vHistEdges(1:end-1)+diff(vHistEdges)./2;
    plot(vHistCenters,vHistCount/100 + 12-iMonth+1,'LineWidth',2);hold on;
    minV(iMonth)=min(vHistEdges);
    maxV(iMonth)=max(vHistEdges);
end
title(['Voltage histogram at bus ' num2str(histBusNr)]);
ylabel('Month');
xlabel('Voltage (line-to-neutral) [V]');
xAxisTicks=round(min(minV)):2*mean(diff(vHistEdges)):round(max(maxV))+1;
set(gca,'Xtick',xAxisTicks,'Ytick',1:12,'Xlim',[round(min(minV)) round(max(maxV))+1],'YTickLabel',...
    fliplr({'January','February','March','April',...
    'May','June','July','August',...
    'September','October','November','December'}));
xtickangle(45);
% Draw limit lines
%line(1.1*[230 230],[0 13], 'Color', 'r');  % Lower limit line
%line(0.9*[230 230],[0 13], 'Color', 'r');  % Upper limit line
grid on;
clear histBusNr monthsBeginAt vHistCount vHistEdges vHistCenters minV maxV iMonth;